sudo: required

dist: xenial

services:
  - docker

language: bash

before_install:
  - mkdir -p ~/.docker
  - >
    echo '{ "experimental": "enabled" }' > ~/.docker/config.json
  - sudo systemctl restart docker
  - docker version

before_script:
#  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker run --rm --privileged meedamian/simple-qemu:v4.1.0 -p yes
  - sed -ie 's/FROM alpine/FROM arm32v6\/alpine/g' Dockerfile

script:
  - docker build --no-cache -t berkeleydb .
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      travis_retry timeout 5m echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin
      ./travis-deploy.sh
    fi
