name: Build BerkeleyDB

on: [push]

#on:
#  push:
#    tags:
#      - '*'

jobs:
  build:
    name: Build BerkeleyDB
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm
          - arm2
          - aarch64
          - amd64

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Register self-compiled qemu
        if: matrix.arch != 'amd64'
        run: |
          if [[ "${{ matrix.arch }}" == "arm2" ]]; then
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            exit 0
          fi

          docker run --rm --privileged meedamian/simple-qemu:v4.1.0-${{matrix.arch}} -p yes

      - name: Alter Dockerfile to be arch-specific
        if: matrix.arch != 'amd64'
        run: |
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
            sed -ie 's/FROM alpine/FROM arm64v8\/alpine/g' Dockerfile
            exit 0
          fi

          if [[ "${{ matrix.arch }}" == arm* ]]; then
            sed -ie "s/FROM alpine/FROM arm32v7\/alpine/g" Dockerfile
            exit 0
          fi

          exit 1

      - name: Build Berkeleydb stage
        run: >
          DOCKER_BUILDKIT=1 docker build .
          --tag   berkeleydb
          --file  Dockerfile

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u="${GITHUB_ACTOR,,}" --password-stdin

      - name: Tag, and push
        run: |
          DOCKER_SLUG=${GITHUB_REPOSITORY/docker-}
          FULL_TAG="${DOCKER_SLUG,,}:db-4.8.30.NC-${{ matrix.arch }}-${GITHUB_SHA:0:7}"

          docker tag berkeleydb ${FULL_TAG}
          docker push ${FULL_TAG}

  manifest:
    name: Aggregate all images under one manifest
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v1.0.0

      - run: docker version
