name: Build BerkeleyDB

on: [push]

#on:
#  push:
#    tags:
#      - '*'

jobs:
  build:
    name: Build BerkeleyDB
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm
          - aarch64
          - amd64

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Register self-compiled qemu
        if: matrix.arch != 'amd64'
        run: docker run --rm --privileged meedamian/simple-qemu:v4.1.0-${{matrix.arch}} -p yes

      - name: Alter Dockerfile to be arch-specific
        if: matrix.arch != 'amd64'
        run: |
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
            sed -ie 's/FROM alpine/FROM arm64v8\/alpine/g' Dockerfile
            exit 0
          fi

          if [[ "${{ matrix.arch }}" == "arm" ]]; then
            sed -ie "s/FROM alpine/FROM arm32v7\/alpine/g" Dockerfile
            exit 0
          fi

          exit 1

      - name: Build Berkeleydb stage
        run: >
          DOCKER_BUILDKIT=1 docker build .
          --tag   berkeleydb
          --file  Dockerfile

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u="${GITHUB_ACTOR,,}" --password-stdin

      - name: Tag, and push
        run: |
          DOCKER_SLUG=${GITHUB_REPOSITORY/docker-}
          TAG="${DOCKER_SLUG,,}:${{ matrix.arch }}-${GITHUB_SHA:0:16}"

          docker tag berkeleydb ${TAG}
          docker push ${TAG}


  # TODO: only do that on tag
  manifest:
    name: Aggregate all images under one manifest
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Enable manifests
        run: |
          mkdir -p ~/.docker

          echo '{ "experimental": "enabled" }' > ~/.docker/config.json
          sudo systemctl restart docker
          docker version

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u="${GITHUB_ACTOR,,}" --password-stdin

      - name: Process all images
        run: |
          DOCKER_SLUG=${GITHUB_REPOSITORY/docker-}

          ARCHS=(arm aarch64 amd64)

          for arch in ${ARCHS[@]}; do
            TAG="${DOCKER_SLUG,,}:${arch}-${GITHUB_SHA:0:16}"
            docker pull "${TAG}"

            docker tag "${TAG}" "${DOCKER_SLUG,,}:db-4.8.30.NC-${arch}"
            docker push "${DOCKER_SLUG,,}:db-4.8.30.NC-${arch}"
          done

          PREFIX="${DOCKER_SLUG,,}:db-4.8.30.NC"

          docker -D manifest create "${PREFIX}" "${ARCHS[@]/#/${PREFIX}-}"

          docker manifest annotate "${PREFIX}" "${PREFIX}-arm"     --os linux --arch arm   --variant v7
          docker manifest annotate "${PREFIX}" "${PREFIX}-aarch64" --os linux --arch arm64 --variant v8

          docker manifest push "${PREFIX}"
